### ISSUE TITLE
Image based patching

### ISSUE THREAD

**Issue by JohnNilsson** [microsoft/Service-Fabric-POA#24]
In one of the QA-session it was mention that the Patch Orchestration application was not the recommended approach, and that instead "image based patching" should be used.

Could you clarify what was meant with this? Is the POA deprecated? With image based patching did you simply mean [this](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-automatic-upgrade)?

**Comment by khandelwalbrijesh** [comment]
Patch orchestration application on Windows is fully supported while we have pulled back the support for the same on linux. Yes, by image based patching we mean [this](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-automatic-upgrade) only. 
While above approach is suggested to our customers but some of service fabric customers keep using POA due to lack of some crucial features in VMSS OS upgrade.
Let me know if this answers your question so, we can close this.

**Comment by JohnNilsson** [comment]
Well, it would help if you could clarify what those crucial features are to provide some guidelines. Do I want to spend my time maintaining, configuring and upgrading POA, or do I want to spend it removing the current POA installation and configuring VMSS upgrades instead? What would be the pros and cons?

**Comment by khandelwalbrijesh** [comment]
The features like 'scheduling updates' and 'patching the cluster Nodewise' are not there in VMSS Auto OS upgrade. You can make your decision based on requirement of the above features.

**Comment by JohnNilsson** [comment]
Ok, so a fair summary would be that the image based patching will work with the cluster health in basically the same way as the POA, with the same reliability, but being limited in configurability will force you to do full upgrade domains at the time, and won't let you schedule things on, say, weekends. POA is the supported means to achieve this flexibility if desired, but if not, image based patching would be the way to go?

Feel free to close this issue if we are in agreement here.

**Comment by khandelwalbrijesh** [comment]
Agreed.
